# module "pipeline" {
#   source                           = "git@github.com:health-union/tf-hu-bg-pipeline.git?ref=v1.3.2"
#   include_trigger                  = false
#   environment                      = var.environment
#   project                          = var.service
#   container_name                   = var.container_name
#   container_port                   = var.container_port
#   cluster_name                     = data.aws_ecs_cluster.cluster.cluster_name
#   lb_name                          = data.aws_lb.selected.name
#   https_listener                   = data.aws_lb_listener.https.arn
#   https_test_listener              = data.aws_lb_listener.https_test.arn
#   blue_lb_target_group             = data.aws_lb_target_group.blue.name
#   green_lb_target_group            = data.aws_lb_target_group.green.name
#   source_config_bucket             = data.aws_s3_bucket.pipeline_config_bucket.bucket
#   code_deploy_artifact_bucket      = data.aws_s3_bucket.pipeline_artifacts_bucket.bucket
#   ecr_repo                         = data.aws_ecr_repository.service.name
#   deployment_app_name              = "ecs"
#   failure_notification_lambda_name = "${var.environment}-deployment-failure"
# }
